- src/views/nads/form/components/NetworkTypeParameters/components/BridgeParameters/BridgeParameters.tsx
The controller was not connected to the Checkbox component hence the form data was missing the `macspoofchk` property
> CNV-40006: MAC spoof checkbox is not affecting the NAD config

- Dockerfile.art
nginx is not available on rhel 9 so fixing it just like https://github.com/openshift/monitoring-plugin/pull/110/files
> CONSOLE-3992: Fix nginx not available on rhel 9

- src/views/nads/form/utils/types.ts
Changing to use type `bridge` instead of `cnv-bridge` on NAD create form
Before:
After:
> CNV-40092: UI should use type "bridge" instead of "cnv-bridge"

- src/views/nads/form/NetworkAttachmentDefinitionForm.tsx
Using a state to catch the error message, as react-hook-form error objects may change on different errors and no way to know which field to access to get the proper error message
Before:
After:
> Show error message for failed submit

- package.json
- src/utils/models/network-policy.ts
- src/views/networkpolicies/list/components/NetworkPolicyEmptyState.tsx
- src/views/networkpolicies/new/NetworkPolicyConditionalSelector.tsx
- src/views/networkpolicies/new/NetworkPolicyForm.tsx
- src/views/networkpolicies/new/components/NetworkPolicyFormEgress.tsx
- src/views/networkpolicies/new/components/NetworkPolicyFormIngress.tsx
- yarn.lock
The SyncedEditor was not working properly. It had no sidebar. Here the sidebar is important as it shows samples and schema info for the creation. 
Other than that, I had to change something in the form to make the sync work. This means that when you change something in the yaml editor, you can see the change if you switch to form
> CNV-39286: Fix NetworkPolicy SyncedEditor

- src/views/ingresses/list/IngressesList.tsx
Adding empty state to ingress list - last resource that was missing
Before:
After:
> CNV-39283: Adding empty state for ingress list

- src/views/routes/list/RoutesList.tsx
Show the form instead of yaml creation on empty list create button
> fix create button from /~new to /~new/form to show the creation form

- src/views/networkpolicies/list/NetworkPolicyPage.tsx
- src/views/networkpolicies/list/utils.ts
Remove the `useEffect` and set the `activeTabKey` in the Tab `onSelect` .
The `useEffect` was there to change the `activeTabKey` on navigation change but we can even extract that from the location pathname at every render. 
**Before**
https://github.com/user-attachments/assets/4cbb2f62-2883-4127-b983-d9c480e2f095
**After**
https://github.com/user-attachments/assets/289728eb-ae29-4c9b-8b85-cae7f57c1412
> OCPBUGS-39083: fix switching namespaces in policies

- src/utils/components/PodSelectorModal/PodSelectorModal.tsx
don't use `/spec/selector/` but `spec.selector`
> OCPBUGS-39248:  fix pod selector path

- src/utils/resources/shared.ts
- src/views/routes/form/RouteForm.tsx
- Route create link was like `/k8s/ns/:ns/routes` instead of `/k8s/ns/:ns/route.openshift.io~v1~Route` 
- host and path are not required the route form 
The bug reported that some routes gets re-created but seems to be depending on something else. But the plugin. Maybe they are part of some deployments
> OCPBUGS-39250: fix small routes bugs

- Dockerfile
Recently, we added OKD configs for openshift components. The config overrides the base image with a centos image, which doesn't work because the base image for the Dockerfile is an nginx image. To be consistent with other repos and the ART dockerfile, change the nginx base image to a rhel base image, so that prow cando the substitution. This also prevents any CVE vulnerabilities we would have when using the nginx image.
> Use rhel9 base image in Dockerfile

- src/utils/components/SelectMultiTypeahead/Toggle.tsx
Typeahead empty when the user select at least one item
> CNV-47530: fix typehead select on multi policy

- src/utils/components/DetailsItem/LabelList.tsx
> OCPBUGS-41618: switch key with label

- src/views/networkpolicies/new/components/NetworkPolicySelectorPreview/components/hooks/useNetworkPolicyPodPreviewData.ts
> OCPBUGS-39084: normal user have to use projects no namespaces

- src/views/ingresses/details/tabs/details/components/IngressDetailsSection/IngressDetailsSection.tsx
> OCPBUGS-41697: OCPBUGS-41698: Add annotation field in ingress details page

- src/views/routes/form/AlternateService.tsx
- src/views/routes/form/AlternateServicesSection.tsx
The remove function should not be called by a different `useFieldArray` hook.
It should come from the same `useFieldArray` that is used to render the `AlternateService` array
> OCPBUGS-41692: fix remove function

- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyPage.tsx
- fix bug adding unmountOnExit
- remove the label filter as networkpolicy and multinetwrokpolicy do not need them
**Before**
https://github.com/user-attachments/assets/e3d9b41c-8175-47fe-b821-c93f24cfa9c5
**After**
https://github.com/user-attachments/assets/f30379da-3762-49b4-9c6f-a53ba053810f
> CNV-48188: Fix networkpolicy list

- src/views/routes/form/TLSTermination.tsx
- src/views/routes/form/constants.ts
- src/views/routes/form/utils.ts
**Before**
fields persistent even after termination type change
Destination CA cert not present
**After**
Add Destination CA cert (only for re-encrypt)
Make sure that when the user changes the termination type, we remove the unnecessary cert attributes
Passthrough does not want any cert
Re-encrypt also wants Destination CA 
edge does not want destination ca
https://github.com/user-attachments/assets/aebf0f25-be8c-4b4b-834a-46cf1bd9b15f
> OCPBUGS-41699: Add destination ca cert

- src/utils/components/ListEmptyState/ListEmptyState.tsx
- src/utils/components/ListEmptyState/ListErrorState.tsx
- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyPage.tsx
To be consistent with other pages like Checkpus Preferences and InstanceType
**Before**
**After**
> CNV-48190: move title networkpolicies above tabs

- locales/en/plugin__networking-console-plugin.json
- src/views/routes/actions/hooks/useRouteActions.ts
- src/views/routes/details/EditRoute.tsx
- src/views/routes/form/RouteForm.tsx
- src/views/routes/form/RouteFormActions.tsx
- src/views/routes/form/RouteFormPage.tsx
- src/views/routes/form/useIsCreationForm.tsx
- src/views/routes/form/utils.ts
- src/views/routes/manifest.ts
Edit route form. Before this the edit route action was just a link to the yaml details page
https://github.com/user-attachments/assets/ceee1e72-5bc2-42b1-a2f4-ae9daf62c76f
> OCPBUGS-42311: Route edit form

- locales/en/plugin__networking-console-plugin.json
- src/views/routes/form/TLSTermination.tsx
`&apos;` is html and it means `'`
> OCPBUGS-42134: fix html in translations

- src/utils/utils/sorting.ts
- src/views/ingresses/list/hooks/useIngressColumns.tsx
- src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
- src/views/routes/list/hooks/useRouteColumns.ts
- src/views/routes/list/utils/utils.ts
- src/views/services/list/components/ServiceRow.tsx
- src/views/services/list/hooks/useServiceColumn.tsx
Fix sorting on object fields .
The path referring to is an object so comparing two objects as strings was not working. Sorting randomly.
Now the object is transformed as a string key=value and can order everything using this string
> OCPBUGS-39249: fix sorting on lists

- src/views/routes/details/hooks/useRouteTabs.ts
Non admin users do not have access to routes metrics
**Before**
**After**
> OCPBUGS-42354: hide routes metrics non-admin users

- src/views/routes/list/hooks/useRouteColumns.ts
- src/views/routes/list/utils/utils.ts
Add status list sorting 
**Before**
No status order
**After**
> OCPBUGS-43034: Routes list sort by status

- src/views/routes/list/RoutesList.tsx
Before
within one project
`All Projects` selected
After
within one project
`All Projects` selected
> OCPBUGS-43873 Routes list page shows correct status and location

- yarn.lock
upgrade css-loader to have min `8.4.31` in postcss. With this upgrade we'll use `8.4.49`
upgrade cypress, eslint and resolve-url-loader to have cross-spawn min `7.0.5`. With the upgrade, we'll use `7.0.6`
> OCPBUGS-44396: OCPBUGS-44680: upgrade packages for cve

- src/utils/constants/index.ts
- src/utils/constants/nads.ts
- src/utils/constants/udns.ts
- src/utils/models/index.ts
- src/views/nads/form/NetworkAttachmentDefinitionFormPage.tsx
- src/views/udns/form/UserDefinedNetworkFormPage.tsx
<h2 id="feature-fix">CONSOLE Features and Fixes:</h2>
https://issues.redhat.com/browse/CNV-52127
<h2 id="solution-description">Solution description</h2> 
There was a race condition between reading the i18n resource json and trying to translate certain keys, notably ones where the `t` function is called within a constant instead of another React hook or React component. This PR moves the calling of those `t` functions to when they're used by the React components
<h2 id="reviewers-and-assignees">Reviewers and assignees:</h2>
/cc @upalatucci 
There should be additional checks in the dynamic plugins (e.g., running `e2e-gcp-console`) so that i18n issues don't happen as often (as it did this time and with other plugins). pinging @rhamilto @spadgett about implementing that
<h2 …
> CNV-52127: remove `t` calls that are not within components

- src/utils/constants/index.ts
- src/utils/constants/nads.ts
- src/utils/constants/udns.ts
- src/utils/models/index.ts
- src/views/nads/form/NetworkAttachmentDefinitionFormPage.tsx
- src/views/udns/form/UserDefinedNetworkFormPage.tsx
manual backport of #143 for 4.18 when it merges and is verified
> [release-4.18] CNV-52128: remove t calls that are not within components

- src/utils/components/SelectMultiTypeahead/utils.ts
- src/utils/resources/udns/constants.ts
- src/views/createprojectmodal/CreateProjectModal.tsx
- src/views/createprojectmodal/utils.ts
- src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
- src/views/udns/list/components/utils.ts
For user is difficult to use matchLabels. Use Project selection with `matchExpressions`
use `matchExpressions` also to add projects to a ClusterUDN in the project creation modal
**Before**
**After**
https://github.com/user-attachments/assets/d58414ef-750c-470f-91d4-b77b43fdfda5
https://github.com/user-attachments/assets/b35306e5-e03c-459b-91d2-d0a516968815
> CNV-46603: select projects with multitypeahead

- src/views/services/details/tabs/details/ServiceAddress.tsx
Services in pending state had no ips assigned, which resulted to a crash when a ServiceIPsRow component tried to read those undefined ips. Conditional unwrap of the ips fixed this issue. Restructed the component ServiceAddress.
Before:
https://github.com/user-attachments/assets/78a5c98e-d2f8-4784-9088-72ef4d9475cb
After:
https://github.com/user-attachments/assets/243661e8-8481-41c0-858e-0f3aaadef154
> OCPBUGS-45050: UI crash accessing a Service in pending state

- src/views/createprojectmodal/components/DetailsProjectTab.tsx
- src/views/createprojectmodal/constants.ts
- src/views/createprojectmodal/types.ts
the create project request is differently represented respect to the project created.
The create project request wants:
```{ 
metadata: {
name
}, 
displayName, 
description 
}
```
> OCPBUGS-46557: fix project displayName and description

- src/utils/models/network-policy.ts
- src/views/networkpolicies/new/components/NetworkPolicyFormPorts.tsx
Ports can be a name or number. The name should be alphanumeric and with at least an a-z character.
If it's a number, we should parse it.
**Before**
**After**
> OCPBUGS-46553: fix ports as number instead of strings

- yarn.lock
`path-to-regex` from `0.1.7` (used by `express` that was used by `webpack-dev-server`) to `0.1.12`
> OCPBUGS-48206: fix path-to-regex CVE

- src/utils/resources/udns/helper.ts
- src/views/udns/list/UserDefinedNetworksList.tsx
- src/views/udns/list/components/UDNListCreateButton.tsx
The udn create modal creates only primary udns and you should not be able to create multiple primary udns for one namespace. If you select a namespace, do not let the user create a namespace primary udn if one already exists
> CNV-54828: fix udn create button

- src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
- src/views/udns/list/components/utils.ts
Disable button udn creation when no namespace is selected
> CNV-55129: Disable udn button

- locales/en/plugin__networking-console-plugin.json
- src/utils/utils/constants.ts
- src/views/udns/list/components/UserDefinedNetworkRow.tsx
Seems like the cudn works on all the namespaces.
At least take the namespace column empty at this point so there is no confusion about the resource namespace and the namespace that cudn manage
**Before**
**After**
> CNV-55234: do not show all namesapces in cudn namespace column

- plugin-manifest.ts
Removing the custom project modal with udn creation flow as networking team found some issues with that. 
They have to implement a mechanism to create project with primary udn with just one HTTP request. 
Having to do two requests ( one for creating the project and one for creating the udn) is having some issues. 
This issue is not UI related as the same thing happens with cli 
**What people will see after this**
> CNV-55457: Remove project modal

- src/views/routes/form/AlternateService.tsx
- src/views/routes/form/RouteFormPage.tsx
- src/views/routes/form/ServiceSelector.tsx
- src/views/routes/form/networking-route-form.scss
Service weight is a number input between 0 and 255 so there is no reason should be so big
**Before**
**After**
> OCPBUGS-45803: Fix weight width

- src/utils/resources/nads/helpers.ts
Nad with no label is crashing the nad list as `Object.keys` throw an exception when the input is undefined
> Fix nads with no label

- src/utils/resources/udns/types/types.ts
- src/views/createprojectmodal/constants.ts
- src/views/udns/form/components/UDNLayer2Parameters.tsx
- src/views/udns/form/utils/utils.ts
- src/views/udns/list/components/utils.ts
Just before UDN GA, they changed the spec structure a little bit
**Alert**
> CNV-56336: fix ipam lifecycle with new spec

- src/utils/constants/documentation.tsx
- src/views/ingresses/list/IngressesList.tsx
- src/views/nads/list/NetworkAttachmentDefinitionList.tsx
- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
- src/views/routes/list/RoutesList.tsx
- src/views/services/list/ServiceList.tsx
- src/views/udns/list/UserDefinedNetworksList.tsx
1. consolidate documentation links in one file
2. provide links for routes and multiple networks with
upstream/downstream switching
3. provide static k8s links to network services and ingress
> OCPBUGS-42135: Update documentation links

- src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
We had two FormGroup components nested. Now we have FormSection (Projects label) with FormGroup inside (match labels)
**Before**
**After**
> CNV-56236: fix cudn modal form titles

- src/views/routes/form/utils.ts
Do not use a default path. IT's not a required parameter to create route
> OCPBUGS-41964: No default path in the route creation form

- src/utils/components/LabelSelectorEditor/LabelSelectorEditor.tsx
Correctly deletes label row.
Before:
https://github.com/user-attachments/assets/d034a174-0bfb-4f66-9af9-2453cd76dfbd
After:
https://github.com/user-attachments/assets/a970e6f9-5978-48eb-bb11-3f8808ff1d63
> CNV-58015: fix delete label row

- src/views/ingresses/details/tabs/details/components/IngressRulesSection/IngressRulesSection.tsx
- src/views/ingresses/details/tabs/details/components/IngressRulesSection/RulesHeader.tsx
- src/views/ingresses/details/tabs/details/components/IngressRulesSection/RulesRow.tsx
- src/views/ingresses/details/tabs/details/components/IngressRulesSection/RulesRows.tsx
- src/views/nads/list/components/NADsRow/NADsRow.tsx
- src/views/nads/list/hooks/useNADsColumns.tsx
- src/views/networkpolicies/details/tabs/details/components/NetworkPolicyDetailsEgress.tsx
- src/views/networkpolicies/details/tabs/details/components/NetworkPolicyDetailsRow/NetworkPolicyDetailsRow.tsx
- src/views/networkpolicies/list/components/NetworkPolicyRow.tsx
- src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
- src/views/routes/details/components/tabs/detailsTab/components/RouteIngressStatusSection/ConditionRow.tsx
- src/views/routes/details/components/tabs/detailsTab/components/RouteIngressStatusSection/Conditions.tsx
- src/views/services/list/hooks/useServiceColumn.tsx
- src/views/udns/list/components/UserDefinedNetworkRow.tsx
- src/views/udns/list/hooks/useUDNColumns.tsx
- replaces `co-m-table-grid` and related classes with PatternFly `Table` 
- removes `dropdown-kebab-pf` classes
Before:
After:
> CNV-59853: remove co-m-table-grid and dropdown-kebab-pf classes

- src/views/udns/list/components/UserDefinedNetworkCreateForm.tsx
the input was not changing the state and cudn got created with the original generated name. 
The `name` prop was overlapping with `react-hook-form` library `register` method
> CNV-60065: fix cudn input name

- src/utils/constants/documentation.tsx
Uses links to upstream documentation in case no downstream `documentationBaseURL` is provided in `SERVER_FLAGS`
Before:
https://github.com/user-attachments/assets/365a0980-ea0a-434a-833b-73002161f26b
After:
https://github.com/user-attachments/assets/fcb19046-b75f-4b9b-865d-72bfe25e2998
> CNV-60062: fix links to upstream documentation

- src/utils/components/DetailsItem/DetailsItem.tsx
- src/utils/components/DetailsItem/swagger.ts
- short term fix, it is a copy of console code
- sometimes it takes a while to fetch the description so the popover content might not show up immediately
- we should rely on `getSwaggerPropertyDescription` function from `console-dynamic-plugin-sdk` once it is exposed, this is a PR in console to expose it: https://github.com/openshift/console/pull/15075
Before:
After:
https://github.com/user-attachments/assets/d5a8f5bd-a61a-42b1-8144-a67fdc93e9ff
(don't mind the styling issues, those are fixed by another PR)
> CNV-61902: fetch description of terms for popovers

- locales/en/plugin__networking-console-plugin.json
- locales/es/plugin__networking-console-plugin.json
- locales/fr/plugin__networking-console-plugin.json
- locales/ja/plugin__networking-console-plugin.json
- locales/ko/plugin__networking-console-plugin.json
- locales/zh/plugin__networking-console-plugin.json
- src/utils/resources/udns/selectors/index.ts
- src/views/udns/actions/UDNActions.tsx
- src/views/vmnetworks/details/VMNetworkPage.tsx
- src/views/vmnetworks/details/components/VMNetworkTitle.tsx
- src/views/vmnetworks/details/tabs/NetworkDetailPage.tsx
- src/views/vmnetworks/details/tabs/NetworkYAMLPage.tsx
- src/views/vmnetworks/list/components/VMNetworkRow.tsx
- src/views/vmnetworks/manifest.ts
We need to add row columns specific to vm network and change the actions
I had to create this detail page to have a separate route specific for the VM network (the vm network its just a ClusterUserDefinedNetwork with localnet  specs) 
DEMO
https://github.com/user-attachments/assets/397e9ebb-d7d4-46f9-b981-b2154c066436
> CNV-52160: Vmnetwork details page

- src/views/vmnetworks/actions/components/EditProjectMappingModal.tsx
- src/views/vmnetworks/constants.ts
- src/views/vmnetworks/details/components/VMNetworkTitle.tsx
- src/views/vmnetworks/form/VMNetworkNewForm.tsx
- src/views/vmnetworks/list/VMNetworkList.tsx
- src/views/vmnetworks/list/components/VMNetworkRow.tsx
- src/views/vmnetworks/manifest.ts
- fixes wizard cancel button, which was not closing the wizard before
- refactoring with a `VM_NETWORKS_PATH` constant
After:
https://github.com/user-attachments/assets/4451a10e-4060-4a3b-8a4c-a71807643edd
> CNV-68676: fix wizard cancel button

- src/views/vmnetworks/manifest.ts
`CAN_LIST_NS` is the flag that we use to determine if the user is an admin
usage: `useIsAdmin` hook
> OCPBUGS-61531: show VM network menu only on admin
