openshift/networking-console-plugin

- integration-tests/tests/example-page.cy.ts
leave teh e2e code as it can be useful in the future
> Skip fake e2e test

- Dockerfile
- Dockerfile.art
Dockerfile requested by the art team to have a build
Dockerfile.art use cachito for yarn dependencies
Taking that from the nmstate console plugin
> Fix Dockerfile for ART development

- src/views/nads/actions/NADActions.tsx
- src/views/nads/actions/hooks/useNADsActions.tsx
- src/views/nads/list/components/NADsRow/NADsRow.tsx
> CNV-39943: Improve NAD actions

- src/templates/service.ts
> Fix service no apiGroup in ServiceModel

- src/utils/components/SelectMultiTypeahead/SelectMultiTypeahead.tsx
- src/utils/components/SelectMultiTypeahead/Toggle.tsx
Fix crashes for poliicy for select typeahead
> CNV-36170: Fix multi network policy policyFor select typeahead

- src/views/nads/list/NetworkAttachmentDefinitionList.tsx
Before:
https://github.com/openshift/networking-console-plugin/assets/67270715/9905d2da-006d-4d13-93b0-9d41ad7418ce
After:
https://github.com/openshift/networking-console-plugin/assets/67270715/d211a21d-c6a9-4833-baa4-00b90d0b4945
> List button create redirects to create from YAML instead of form

- src/views/nads/details/tabs/details/NADTypeDetails.tsx
- src/views/nads/form/utils/types.ts
- src/views/nads/form/utils/utils.ts
Before:
https://github.com/openshift/networking-console-plugin/assets/67270715/21c570f1-cfdc-4345-9916-fe30d793fcd4
After:
https://github.com/openshift/networking-console-plugin/assets/67270715/f905e58e-7e50-4b98-ac38-d1daf896a234
> CNV-41506: Localnet NAD incorrectly typed

- src/views/ingresses/manifest.ts
- src/views/nads/manifest.ts
- src/views/networkpolicies/manifest.ts
- src/views/routes/manifest.ts
- src/views/services/manifest.ts
https://issues.redhat.com//browse/OCPBUGS-38923
Opening on behalf of @rhamilto as he isn't able to fork this repo
> OCPBUGS-38923: Replace hardcoded strings with internationalized version

- src/views/ingresses/list/IngressesList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
- src/views/routes/list/RoutesList.tsx
- src/views/services/list/ServiceList.tsx
> OCPBUGS-39247: fix docs links

- src/utils/utils/sorting.ts
- src/views/ingresses/list/hooks/useIngressColumns.tsx
- src/views/ingresses/list/utils/utils.ts
- src/views/nads/list/hooks/useNADsColumns.tsx
- src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
- src/views/routes/list/components/RouteRow.tsx
- src/views/routes/list/hooks/useRouteColumns.ts
- src/views/services/list/hooks/useServiceColumn.tsx
Sorting method to sort matchLabels pod selector in network policies
specify an ingress method for hosts
fix small things for routes and service
> OCPBUGS-39249: fix Sort all resources list

- src/utils/models/network-policy.ts
- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/new/NetworkPolicyForm.tsx
- src/views/networkpolicies/new/NetworkPolicyFormSections.tsx
fix when using NetworkPolicyModel and when MultiNetworkPolicy
Small fix: doc link on the empty list state
> CNV-48187: Create MultiNetworkPolicy instead of NetworkPolicy

- src/views/routes/list/components/RouteRow.tsx
small fix on the link creation
> OCPBUGS-41578: fix router link

- locales/en/plugin__networking-console-plugin.json
- src/custom.d.ts
- src/utils/components/ListEmptyState/ListEmptyState.tsx
- src/utils/components/ListEmptyState/ListErrorState.tsx
- src/utils/components/ListEmptyState/ListSkeleton.tsx
- src/utils/components/ListEmptyState/list-error-state.scss
- src/utils/components/ListEmptyState/restricted-sign.svg
- src/views/ingresses/list/IngressesList.tsx
- src/views/nads/list/NetworkAttachmentDefinitionList.tsx
- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
- src/views/routes/list/RoutesList.tsx
- src/views/services/list/ServiceList.tsx
Adding to `ListEmptyState` the error states and changing the loading with the skeleton. 
Before
Infinite loading 
Error not showing up basically 
After
> OCPBUGS-41501: Add status box for error handling

- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
fix1: Show pagination on filtered data 
fix2: slice the list to show just the paginated data
> OCPBUGS-41590: fix networkpolicy pagination

- src/views/routes/form/TLSTermination.tsx
> OCPBUGS-41699: OCPBUGS-41695: fix clear fileupload not working

- locales/en/plugin__networking-console-plugin.json
- src/utils/components/ErrorPage/ErrorPage.tsx
- src/utils/components/ErrorPage/error-page.scss
- src/utils/components/StatusBox/StatusBox.tsx
- src/views/ingresses/details/IngressDetailsPage.tsx
- src/views/networkpolicies/details/NetworkPolicyDetailsPage.tsx
- src/views/routes/details/RouteDetailsPage.tsx
- src/views/services/details/ServiceDetailsPage.tsx
**Before**
infinite loading
**After**
> OCPBUGS-41693: Add Error page for not found resources and other errors

- src/utils/utils/sorting.ts
- src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
- src/views/networkpolicies/list/NetworkPolicyList.tsx
- src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
Pagination + sorting = not working pagination
**Before**
**After**
> OCPBUGS-42141: fix pagination during sorting

- locales/en/plugin__networking-console-plugin.json
- src/views/routes/form/AlternateService.tsx
- src/views/routes/form/RouteForm.tsx
- src/views/routes/form/ServiceSelector.tsx
- src/views/routes/form/Targetport.tsx
- src/views/routes/form/constants.ts
Added service weight
small fix: change `SERVICE_FIELD_ID` value;
**Before**
**After**
> OCPBUGS-41969: OCPBUGS-42352: add service weight

- src/views/nads/manifest.ts
- src/views/networkpolicies/manifest.ts
- src/views/routes/manifest.ts
From virt perspective, when the user go to the RoutePage, the perspective change to admin. We don't want that behavior
> CNV-49305: fix for virt perspective

- src/utils/constants/routes.ts
- src/views/routes/list/RoutesList.tsx
- src/views/routes/list/hooks/useRouteFilters.ts
- src/views/routes/list/utils/utils.ts
> OCPBUGS-43034: Add Route Filter in route list

- start-console.sh
- webpack.config.ts
Run kubevirt-plugin using the start-console.sh script
needs https://github.com/kubevirt-ui/kubevirt-plugin/pull/2292
> run kubevirt-plugin using start-console

- locales/en/plugin__networking-console-plugin.json
- src/utils/resources/nads/constants.ts
- src/utils/resources/nads/helpers.ts
- src/views/nads/actions/hooks/useNADsActions.tsx
- src/views/nads/list/components/NADsRow/NADsRow.tsx
> CNV-54111: mark NAD managed by UDN

- src/views/udns/manifest.ts
**WIthout UDN CRD installed**
**With UDN CRD installed**
> OCPBUGS-44823: hide udn navbar when udn is not installed

- locales/en/plugin__networking-console-plugin.json
- src/views/createprojectmodal/components/SelectClusterUDN.tsx
> CNV-54827: fix select label on ClusterUserDefinedNetwork

- src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
- src/views/udns/list/components/utils.ts
> CNV-55239: Cluster udn through matchlabel

- locales/en/plugin__networking-console-plugin.json
- src/views/nads/list/NetworkAttachmentDefinitionList.tsx
- src/views/nads/list/components/NADListEmpty/NADListEmpty.tsx
nad name misspelled
https://issues.redhat.com/secure/attachment/13328391/console_bug.png
> OCPBUGS-48677: fix nad misspelled

- src/utils/resources/udns/selectors/index.ts
- src/views/udns/list/components/UserDefinedNetworkRow.tsx
- src/views/udns/list/hooks/useUDNColumns.tsx
> OCPBUGS-48440: show MTU and sort on list

- src/utils/components/ListEmptyState/ListEmptyState.tsx
- src/views/udns/list/UserDefinedNetworksList.tsx
There was no CUDN creation button in the empty state. 
**Before**
**After**
> CNV-56076: create cudn from empty state

- locales/en/plugin__networking-console-plugin.json
- src/views/udns/details/tabs/details/UDNLayer2Details.tsx
> CNV-56436: show ipam lifecycle correctly with new spec

- src/utils/components/DetailsItem/DetailsItem.tsx
- src/utils/components/LabelSelectorEditor/LabelSelectorEditor.tsx
- src/utils/components/Selector/utilts.ts
- src/views/routes/details/components/tabs/detailsTab/components/RouteDetailsSection/DetailsSectionLeftColumn.tsx
- src/views/routes/details/components/tabs/detailsTab/components/RouteDetailsSection/DetailsSectionRightColumn.tsx
- src/views/routes/details/components/tabs/detailsTab/components/RouteDetailsSection/RouteDetailsSection.tsx
- src/views/services/details/tabs/details/ServiceAddress.tsx
- src/views/services/details/tabs/details/ServiceDetails.tsx
- src/views/services/details/tabs/details/ServicePortMapping.tsx
- Replaces Bootstrap Grid CSS with PatternFly Grid and Table
- also fixes requirement.values is undefined error
Before:
After:
> CNV-63471: Replace Bootstrap Grid CSS with PatternFly Grid and Table

- src/views/ingresses/details/tabs/details/components/IngressDetailsSection/IngressDetailsSection.tsx
> OCPBUGS-60122: Fix ingress details

- OWNERS
> New OWNERS list
